
import xml.dom.minidom
import os
from xml.etree import ElementTree as ET

def get_kv(path):
    if not os.path.exists(path): return {}
    try:
        tree = ET.parse(path)
        root = tree.getroot()
        return {child.attrib['name']: (child.text, child.attrib.get('translatable', 'true')) for child in root if child.tag == 'string'}
    except:
        return {}

def write_xml(path, en_kv, target_kv, new_translations):
    doc = xml.dom.minidom.Document()
    root = doc.createElement('resources')
    doc.appendChild(root)

    final_kv = {}
    for name, (text, trans) in en_kv.items():
        if name in target_kv:
            final_kv[name] = target_kv[name]
        elif name in new_translations:
            final_kv[name] = (new_translations[name], 'true')
        else:
            final_kv[name] = (text, 'true')

    for name in sorted(final_kv.keys()):
        val, trans = final_kv[name]
        s_node = doc.createElement('string')
        s_node.setAttribute('name', name)
        if trans == 'false':
            s_node.setAttribute('translatable', 'false')
        if val:
            s_node.appendChild(doc.createTextNode(val))
        root.appendChild(s_node)

    with open(path, 'w', encoding='utf-8') as f:
        content = doc.toprettyxml(indent='  ', encoding='utf-8').decode('utf-8')
        # Fix the issue where toprettyxml adds empty lines
        content = "\n".join([line for line in content.splitlines() if line.strip()])
        f.write(content)

en_path = 'app/src/main/res/values/strings.xml'
en_kv = get_kv(en_path)

# PT-BR / PT
pt_translations = {
    'actionClearGameCoverArt_summary': 'Limpar arte da capa personalizada definida anteriormente',
    'actionClearGameCoverArt_title': 'Limpar arte da capa',
    'actionClearGameCoverArt_toast': 'A arte da capa foi limpa',
    'actionConnectNetplay_summary': 'Conectar a um servidor netplay com este jogo.',
    'actionConnectNetplay_title': 'Conectar netplay',
    'actionCreateShortcut_summary': 'Adicionar um atalho para esta ROM no lançador de apps padrão',
    'actionCreateShortcut_title': 'Criar atalho',
    'actionDeleteGameData_confirmation': 'Tem certeza de que deseja excluir todos os dados deste jogo do armazenamento interno?',
    'actionDeleteGameData_summary': 'Excluir dados deste jogo do armazenamento interno. Dados no armazenamento externo serão mantidos.',
    'actionDeleteGameData_title': 'Excluir dados',
    'actionOpenMenu': 'Abrir menu principal',
    'actionRemove_summary': 'Remover da biblioteca',
    'actionRemove_title': 'Remover',
    'actionSearchRoms': 'Procurar ROMs',
    'actionSetGameCoverArt_summary': 'Alterar arte da capa para uma imagem personalizada',
    'actionSetGameCoverArt_title': 'Alterar arte da capa',
    'actionStartNetplay_summary': 'Iniciar servidor netplay com este jogo.',
    'actionStartNetplay_title': 'Servidor netplay',
    'actionStart_summary': 'Reiniciar o jogo',
    'actionStart_title': 'Iniciar',
    'angrylion_busyloop_title': 'Loop ocupado enquanto espera por trabalho',
    'angrylion_compatibility_mode_fast': 'Rápido',
    'angrylion_compatibility_mode_moderate': 'Moderado',
    'angrylion_compatibility_mode_slow': 'Lento',
    'angrylion_compatibility_mode_title': 'Modo de compatibilidade',
    'angrylion_hide_overscan_title': 'Ocultar overscan',
    'angrylion_num_workers_title': 'Número de threads de trabalho',
    'angrylion_parallel_mode_title': 'Modo multithread',
    'angrylion_vi_integer_scaling_title': 'Escalonamento inteiro',
    'angrylion_vi_interpolation_entry_linear': 'Linear',
    'angrylion_vi_interpolation_entry_nearest_neighbor': 'Vizinho Mais Próximo',
    'angrylion_vi_interpolation_title': 'Interpolação VI',
    'angrylion_vi_mode_entry_coverage': 'Cobertura',
    'angrylion_vi_mode_entry_depth': 'Profundidade',
    'angrylion_vi_mode_entry_filtered': 'Filtrado',
    'angrylion_vi_mode_entry_unfiltered': 'Sem filtro',
    'angrylion_vi_mode_title': 'Modo VI',
    'assetExtractor_error': 'Erro',
    'assetExtractor_failed_permissions': 'Este aplicativo não pode prosseguir sem estas permissões',
    'assetExtractor_permissions_rationale': 'O Mupen64Plus AE precisa ser capaz de:\\nLer seu armazenamento para ler arquivos ROM, save states e configurações.\\nGravar em seu armazenamento para gravar configurações e dados de salvamento.',
    'assetExtractor_permissions_rationale_notifications': 'O Mupen64Plus AE precisa ser capaz de mostrar notificações para exibir o status dos serviços em primeiro plano.',
    'assetExtractor_permissions_title': 'Permissões',
    'audioBufferSize_title': 'Tamanho do Buffer de Áudio',
    'audioFloatingPoint_summary': 'Áudio FP de maior qualidade. Alguns dispositivos podem não ser compatíveis.',
    'audioFloatingPoint_title': 'Amostras de Ponto Flutuante',
    'audioLowPerformanceMode_summary': 'Melhor desempenho ao custo da latência de áudio.',
    'audioLowPerformanceMode_title': 'Modo de baixo desempenho',
    'audioSamplingType_soundtouch': 'SoundTouch',
    'audioSamplingType_title': 'Tipo de Amostragem',
    'audioSamplingType_trivial': 'Trivial',
    'audioTimeStretch_summary': 'Ativa o alongamento de tempo de áudio para reduzir estalos, mas introduz atraso no áudio',
    'audioTimeStretch_title': 'Alongamento de tempo de áudio',
    'audioVolume_title': 'Volume do Áudio',
    'buttonsConfig_buttonsAB': 'Botões A/B',
    'buttonsConfig_buttonsC': 'Botões C',
    'buttonsConfig_separate': 'Usar botões separados',
    'categoryAngrylion_title': 'Configurações do Angrylion RDP Plus',
    'categoryGlide64Advanced_title': 'Configurações avançadas do Glide64',
    'categoryLibrary_title': 'Biblioteca',
    'categoryNetplay_title': 'Netplay',
    'categoryParallel_title': 'Configurações do Parallel RDP',
    'categoryShaders_title': 'Shaders',
    'cheatEditor_add': 'Adicionar cheat',
    'cheatEditor_add_advanced': 'Adicionar cheat avançado',
    'cheatEditor_add_cheats': 'Adicionar cheat',
    'cheatEditor_add_option': 'Adicionar opção',
    'cheatEditor_edit1': 'Editar cheat',
    'cheatEditor_edit2': 'Edição avançada de cheat',
    'cheatEditor_hint_cheatAddress': 'Endereço',
    'cheatEditor_hint_cheatData': 'Inserir dados do cheat',
    'cheatEditor_hint_cheatNotes': 'Notas do Cheat (opcional)',
    'cheatEditor_hint_cheatTitle': 'Título do Cheat',
    'cheatEditor_hint_optionData': 'Inserir dados da opção',
    'cheatEditor_hint_value': 'Valor',
    'cheatEditor_hint_value_description': 'Descrição',
    'cheatEditor_invalid_value': 'N/D',
    'cheatEditor_remove_option': 'Remover opção',
    'clearTexturePack_message': 'Selecione um pacote de texturas para excluir',
    'confirmClearData_message': 'Tem certeza de que deseja limpar o pacote de texturas de alta resolução selecionado?',
    'confirmRemoveFromLibrary_message': 'Tem certeza de que deseja remover este jogo da biblioteca?',
    'controller_buttonSensor': 'Botão de alternar sensor',
    'coreFragment_sdcard_write_error': 'Não foi possível gravar a configuração no cartão SD',
    'defaultsAllEmulatedControllersAlwaysAttached_summary': 'Se ativado, todos os controles emulados estarão conectados ao N64 emulado, independentemente de haver controles reais suficientes conectados.',
    'defaultsAllEmulatedControllersAlwaysAttached_title': 'Todos os controles emulados estão sempre conectados',
    'defaultsAutoPlayerMapping_summary': 'Mapeia um controle para o próximo jogador N64 disponível durante o jogo ao pressionar um botão',
    'defaultsAutoPlayerMapping_title': 'Mapeamento automático de jogadores',
    'disableExtraMem_title': 'Desativar pack de expansão',
    'disk64ddPath_title': 'Disco 64DD (ndd)',
    'displayFps_entryBottomCenter': 'Centro inferior',
    'displayFps_entryBottomLeft': 'Inferior esquerdo',
    'displayFps_entryBottomRight': 'Inferior direito',
    'displayFps_entryOff': 'Desligado',
    'displayFps_entryTopCenter': 'Centro superior',
    'displayFps_entryTopLeft': 'Superior esquerdo',
    'displayFps_entryTopRight': 'Superior direito',
    'displayOrientation_entryAuto': 'Automático',
    'displayResolution_entry1440x1080': '1440 x 1080',
    'displayResolution_entry1920x1440': '1920 x 1440',
    'displayResolution_entry2160x1620': '2160 x 1620',
    'displayResolution_entry2880x2160': '2880 x 2160',
    'displayResolution_entry3840x2880': '3840 x 2880',
    'displayResolution_entry4320x3240': '4320 x 3240',
    'displayResolution_entry5120x3840': '5120 x 3840',
    'displayResolution_entry5760x4320': '5760 x 4320',
    'displayScaling_entryOriginal': 'Original\\n<small>Preencher tela, sem distorção (adiciona barras pretas)</small>',
    'displayScaling_entryStretch169': 'Esticar 16:9\\n<small>Altera a proporção da imagem para 16:9 (adiciona distorção)</small>',
    'displayZoomDefault_summary': 'Desmarque para especificar um valor de zoom personalizado para este jogo',
    'displayZoomDefault_title': 'Usar zoom padrão',
    'displayZoom_title': 'Zoom',
    'extractRomTask_title': 'Preparando dados do jogo…',
    'fix_GLideN64_summary': 'Corrige problemas em alguns dispositivos que mostram a tela de cabeça para baixo com GLideN64',
    'fix_GLideN64_title': 'Corrigir tela invertida',
    'gallerySortingMethod_entryFileName': 'Nome do arquivo',
    'gallerySortingMethod_entryRomName': 'Nome da ROM',
    'gallerySortingMethod_title': 'Ordenar',
    'gameDataStorageExternalPath_title': 'Local de dados de jogo externo',
    'gameDataStorageLocation_entryExternal': 'Externo',
    'gameDataStorageLocation_entryInternal': 'Interno',
    'gameDataStorageLocation_title': 'Local de armazenamento de dados do jogo',
    'glide64mk2_adjust_aspect_title': 'Ajustar aspecto da tela para o modo widescreen',
    'glide64mk2_alt_tex_size_title': 'Método alternativo de tamanho de textura',
    'glide64mk2_aspect_force_16_9': 'Forçar 16:9',
    'glide64mk2_aspect_force_4_3': 'Forçar 4:3',
    'glide64mk2_aspect_original': 'Original',
    'glide64mk2_aspect_stretch': 'Esticar',
    'glide64mk2_aspect_title': 'Proporção de tela',
    'glide64mk2_buff_clear_title': 'Limpar buffer em cada quadro',
    'glide64mk2_clip_zmax_title': 'Ativar corte de plano distante',
    'glide64mk2_clip_zmin_title': 'Ativar corte z próximo',
    'glide64mk2_correct_viewport_title': 'Forçar viewport positiva',
    'glide64mk2_decrease_fillrect_edge_title': 'Reduzir tamanho do fillrect em 1',
    'glide64mk2_detect_cpu_write_title': 'Mostrar imagens gravadas diretamente pela CPU',
    'glide64mk2_disable': 'Desativar',
    'glide64mk2_enable': 'Ativar',
    'glide64mk2_fast_crc_title': 'Usar algoritmo CRC rápido',
    'glide64mk2_fb_crc_mode_disable': 'Desativar cálculo de CRC',
    'glide64mk2_fb_crc_mode_fast': 'Cálculo de CRC rápido',
    'glide64mk2_fb_crc_mode_safe': 'Cálculo de CRC seguro',
    'glide64mk2_fb_crc_mode_title': 'Definir modo CRC do framebuffer',
    'glide64mk2_fb_hires_title': 'Emulação de buffer de quadro por hardware',
    'glide64mk2_fb_read_alpha_title': 'Ler alfa do framebuffer',
    'glide64mk2_fb_read_always_title': 'Ler framebuffer a cada quadro (pode ser lento, use apenas para efeitos que precisam, ex: transições de Banjo Kazooie, DK64)',
    'glide64mk2_fb_render_title': 'Ativar renderização de profundidade por software',
    'glide64mk2_fb_smart_title': 'Framebuffer inteligente',
    'glide64mk2_filtering_automatic': 'Automático',
    'glide64mk2_filtering_force_bilinear': 'Forçar bilinear',
    'glide64mk2_filtering_force_point_samples': 'Forçar point sampled',
    'glide64mk2_filtering_title': 'Modo de filtragem',
    'glide64mk2_fog_title': 'Névoa',
    'glide64mk2_force_calc_sphere_title': 'Usar apenas mapeamento esférico',
    'glide64mk2_force_microcheck_title': 'Verificar microcódigo a cada quadro',
    'glide64mk2_force_quad3d_title': 'Forçar comando 0xb5 a ser quad, não linha 3D',
    'glide64mk2_game_default': 'Padrão do jogo',
    'glide64mk2_hires_buf_clear_title': 'Limpar buffers de quadro de textura auxiliares',
    'glide64mk2_ignore_aux_copy_title': 'Não copiar buffers de quadro auxiliares',
    'glide64mk2_increase_texrect_edge_title': 'Forçar tamanho do texrect para valor integral',
    'glide64mk2_lodmode_fast': 'Rápido',
    'glide64mk2_lodmode_precise': 'Preciso',
    'glide64mk2_lodmode_title': 'Cálculo de LOD',
    'glide64mk2_n64_z_scale_title': 'Escalar valor z do vértice antes de gravar no buffer de profundidade',
    'glide64mk2_old_style_adither_title': 'Aplicar dither alfa independentemente de alpha_dither_mode',
    'glide64mk2_optimize_texrect_title': 'Renderização rápida de texrect com hwfbe',
    'glide64mk2_pal230_title': 'Definir escala especial para jogos PAL',
    'glide64mk2_read_back_to_screen_mode1': 'Modo 1',
    'glide64mk2_read_back_to_screen_mode2': 'Modo 2',
    'glide64mk2_read_back_to_screen_title': 'Renderizar buffer de quadro do N64 como textura',
    'glide64mk2_stipple_mode_disable': 'Desativar',
    'glide64mk2_stipple_mode_pattern': 'Padrão',
    'glide64mk2_stipple_mode_rotate': 'Rotacionar',
    'glide64mk2_stipple_mode_title': 'Modo de emulação de alfa pontilhado 3DFX',
    'glide64mk2_swapmode_conditional': 'Trocar buffers quando um conjunto de condições for satisfeito. Evita cintilação em alguns jogos',
    'glide64mk2_swapmode_mix': 'Mistura dos dois primeiros métodos',
    'glide64mk2_swapmode_title': 'Método de troca de buffer',
    'glide64mk2_swapmode_vi_ocurred': 'Trocar buffers quando ocorrer interrupção vertical',
    'glide64mk2_texture_correction_title': 'Ativar emulação de correção de textura de perspectiva',
    'glide64mk2_use_sts1_only_title': 'Usar apenas o primeiro SETTILESIZE',
    'glide64mk2_useless_is_useless_title': 'Lidar com fb inalterado',
    'glide64mk2_wrpAnisotropic_16x': '16x',
    'glide64mk2_wrpAnisotropic_1x': '1x',
    'glide64mk2_wrpAnisotropic_2x': '2x',
    'glide64mk2_wrpAnisotropic_4x': '4x',
    'glide64mk2_wrpAnisotropic_8x': '8x',
    'glide64mk2_wrpAnisotropic_title': 'Configuração de filtragem anisotrópica',
    'glide64mk2_zmode_compare_less_title': 'Forçar verificação estrita no teste de buffer de profundidade',
    'gliden64_bilinear_mode_entry_n64_3point': 'N64 3-pontos',
    'gliden64_bilinear_mode_entry_standard': 'Padrão',
    'gliden64_bilinear_mode_title': 'Modo de filtragem bilinear',
    'gliden64_bound_texture_rectangle_coordinates_summary': 'Limita as coordenadas do retângulo texturizado aos valores que eles assumem em resoluções nativas. Evita lixo devido à busca fora dos limites da textura, mas pode resultar em bordas duras.',
    'gliden64_bound_texture_rectangle_coordinates_title': 'Limitar coordenadas do retângulo texturizado',
    'gliden64_category_2d_title': 'Configurações 2D',
    'gliden64_category_fb_title': 'Emulação de Buffer de Quadro',
    'gliden64_category_gamma_title': 'Correção de Gama',
    'gliden64_category_general_title': 'Geral',
    'gliden64_category_texture_filtering_title': 'Filtragem de Textura',
    'gliden64_category_texture_title': 'Textura',
    'gliden64_color_buffer_copy_to_RDRAM_entry_async_mode': 'Copiar em modo assíncrono (2 buffers)',
    'gliden64_color_buffer_copy_to_RDRAM_entry_async_mode_3buffers': 'Copiar em modo assíncrono (3 buffers)',
    'gliden64_color_buffer_copy_to_RDRAM_entry_off': 'Não copiar',
    'gliden64_color_buffer_copy_to_RDRAM_entry_sync_mode': 'Copiar em modo de sincronização',
    'gliden64_color_buffer_copy_to_RDRAM_title': 'Copiar buffer de cor para RDRAM',
    'gliden64_correct_texrect_coords_auto': 'Auto',
    'gliden64_correct_texrect_coords_force': 'Forçar',
    'gliden64_correct_texrect_coords_off': 'Desligado',
    'gliden64_correct_texrect_coords_title': 'Tornar as coordenadas texrect contínuas',
    'gliden64_dithering_mode_rdram_entry_bayer': 'Bayer',
    'gliden64_dithering_mode_rdram_entry_blue_noise': 'Blue Noise',
    'gliden64_dithering_mode_rdram_entry_disable': 'Desativar',
    'gliden64_dithering_mode_rdram_entry_magic_square': 'Quadrado Mágico',
    'gliden64_dithering_mode_rdram_title': 'Modo de pontilhamento para imagem em RDRAM',
    'gliden64_dithering_pattern_summary': 'Ativar padrão de pontilhamento na imagem de saída.',
    'gliden64_dithering_pattern_title': 'Padrão de pontilhamento',
    'gliden64_dithering_quantization_summary': 'Pontilhamento com quantização de cor.',
    'gliden64_dithering_quantization_title': 'Quantização de pontilhamento',
    'gliden64_enable_color_buffer_from_RDRAM_title': 'Cópia do buffer de cor da RDRAM',
    'gliden64_enable_copy_auxiliary_to_RDRAM_title': 'Copiar buffers auxiliares para RDRAM',
    'gliden64_enable_copy_depth_to_RDRAM_entry_hardware': 'Renderizador de hardware',
    'gliden64_enable_copy_depth_to_RDRAM_entry_off': 'Não copiar',
    'gliden64_enable_copy_depth_to_RDRAM_entry_software': 'Renderizador de software',
    'gliden64_enable_copy_depth_to_RDRAM_title': 'Copiar buffer de profundidade para RDRAM',
    'gliden64_enable_coverage_summary': 'Ativa o cálculo de cobertura de pixels. Usado para melhor emulação de mesclagem e modo wire-frame. Precisa de GPU rápida.',
    'gliden64_enable_coverage_title': 'Emulação de cobertura',
    'gliden64_enable_fast_inaccurate_shaders_summary': 'Ativar isso melhorará o desempenho, especialmente na renderização 2D, mas pode ter imprecisões leves ao renderizar texturas.',
    'gliden64_enable_fast_inaccurate_shaders_title': 'Usar shaders mais rápidos',
    'gliden64_enable_fb_emulation_title': 'Emulação de buffer de quadro e/ou profundidade',
    'gliden64_enable_force_depth_buffer_clear': 'Forçar limpeza do buffer de profundidade',
    'gliden64_enable_fragment_depth_write_summary': 'Ativar a gravação da profundidade do fragmento. Alguns dispositivos não são compatíveis.',
    'gliden64_enable_fragment_depth_write_title': 'Profundidade baseada em fragmento',
    'gliden64_enable_halos_removal_summary': 'Isso pode limpar cores estranhas ao redor do texto, mas pode quebrar outras texturas.',
    'gliden64_enable_halos_removal_title': 'Remover halos ao redor de texturas filtradas',
    'gliden64_enable_hw_lighting_title': 'Iluminação por hardware por pixel',
    'gliden64_enable_legacy_blending_summary': 'Desativar isso produz iluminação e névoa mais corretas, mas é mais lento em alguns dispositivos.',
    'gliden64_enable_legacy_blending_title': 'Mesclagem legada',
    'gliden64_enable_lod_title': 'Emulação de LOD',
    'gliden64_enable_n64_depth_compare_title': 'Comparação de profundidade N64',
    'gliden64_enable_native_res_texrects_summary': 'Gráficos 2D mais corretos, mas muito mais lentos e desativa melhorias de textura.',
    'gliden64_enable_native_res_texrects_title': 'Corrigir desalinhamento de imagem texrect',
    'gliden64_enable_softclip_summary': 'Executa o corte de vértices em software, geralmente mais preciso, desative se houver problemas.',
    'gliden64_enable_softclip_title': 'Corte de Vértices por Software',
    'gliden64_force_gamma_correction_title': 'Forçar correção de gama',
    'gliden64_fxaa_summary': 'Anti-Aliasing Aproximado Rápido FXAA',
    'gliden64_fxaa_title': 'FXAA',
    'gliden64_gamma_correction_level': 'Valor de correção de gama',
    'gliden64_hires_noise_dithering_summary': 'Ativar pontilhamento de ruído de alta resolução.',
    'gliden64_hires_noise_dithering_title': 'Pontilhamento de ruído de alta resolução',
    'gliden64_hybrid_filter_summary': 'Ativa o filtro de textura de escalonamento de inteiros híbrido GLideN64. Isso pode prejudicar o desempenho.',
    'gliden64_hybrid_filter_title': 'Filtro híbrido GLideN64',
    'gliden64_max_anisotropic_filtering_title': 'Filtragem anisotrópica máxima',
    'gliden64_render_backgrounds_mode_one_piece': 'Uma peça (rápido)',
    'gliden64_render_backgrounds_mode_stripped': 'Despojado (preciso)',
    'gliden64_render_backgrounds_mode_title': 'Modo de renderização de fundos (apenas HLE)',
    'gliden64_swap_frame_buffers_entry_on_buffer_update': 'Na atualização do buffer',
    'gliden64_swap_frame_buffers_entry_on_vi_origin_change': 'Na mudança de origem VI',
    'gliden64_swap_frame_buffers_entry_on_vi_update': 'Na chamada de atualização VI',
    'gliden64_swap_frame_buffers_title': 'Trocar buffers de quadro',
    'gliden64_threaded_video_summary': 'Ativar backend de vídeo OpenGL multithread',
    'gliden64_threaded_video_title': 'Vídeo multithread GLideN64',
    'gliden64_tx_cache_compression_title': 'Compactar cache de textura',
    'gliden64_tx_cache_size_title': 'Tamanho do cache de texturas filtradas em megabytes',
    'gliden64_tx_deposterize_title': 'Deposterizar textura antes do aprimoramento',
    'gliden64_tx_dump_summary': 'Despejar texturas do jogo conforme encontradas',
    'gliden64_tx_dump_title': 'Despejar texturas',
    'gliden64_tx_enhanced_texture_file_storage_summary': 'Usar armazenamento de arquivos em vez de cache de memória para texturas aprimoradas.',
    'gliden64_tx_enhanced_texture_file_storage_title': 'Armazenamento de arquivo de textura aprimorado',
    'gliden64_tx_enhancement_entry_2xBRZ': '2xBRZ',
    'gliden64_tx_enhancement_entry_3xBRZ': '3xBRZ',
    'gliden64_tx_enhancement_entry_4xBRZ': '4xBRZ',
    'gliden64_tx_enhancement_entry_5xBRZ': '5xBRZ',
    'gliden64_tx_enhancement_entry_6xBRZ': '6xBRZ',
    'gliden64_tx_enhancement_entry_HQ2X': 'HQ2X',
    'gliden64_tx_enhancement_entry_HQ2XS': 'HQ2XS',
    'gliden64_tx_enhancement_entry_HQ4X': 'HQ4X',
    'gliden64_tx_enhancement_entry_LQ2X': 'LQ2X',
    'gliden64_tx_enhancement_entry_LQ2XS': 'LQ2XS',
    'gliden64_tx_enhancement_entry_X2': 'X2',
    'gliden64_tx_enhancement_entry_X2SAI': 'X2SAI',
    'gliden64_tx_enhancement_entry_none': 'Nenhum',
    'gliden64_tx_enhancement_entry_store_as_is': 'Armazenar como está',
    'gliden64_tx_enhancement_title': 'Aprimoramento de Textura',
    'gliden64_tx_filter_ignore_BG_title': 'Não filtrar texturas de fundo',
    'gliden64_tx_filter_mode_entry_none': 'Nenhum',
    'gliden64_tx_filter_mode_entry_sharp1': 'Nítido 1',
    'gliden64_tx_filter_mode_entry_sharp2': 'Nítido 2',
    'gliden64_tx_filter_mode_entry_smooth1': 'Suave 1',
    'gliden64_tx_filter_mode_entry_smooth2': 'Suave 2',
    'gliden64_tx_filter_mode_entry_smooth3': 'Suave 3',
    'gliden64_tx_filter_mode_title': 'Modo de filtro de textura',
    'gliden64_tx_force_16bpp_title': 'Forçar formato de textura de 16 bits para texturas HD',
    'gliden64_tx_hi_res_alt_crc_title': 'Usar cálculo de CRC alternativo',
    'gliden64_tx_hi_res_enable_title': 'Usar pacotes de textura de alta resolução se disponíveis',
    'gliden64_tx_hi_res_full_alpha_channel_title': 'Permitir uso total do canal alfa de texturas de alta resolução',
    'gliden64_tx_hires_texture_file_storage_summary': 'Usar armazenamento de arquivos em vez de cache de memória para texturas de alta resolução.',
    'gliden64_tx_hires_texture_file_storage_title': 'Armazenamento de arquivo de textura de alta resolução',
    'gliden64_tx_save_cache_summary': 'Salva o cache de textura no disco ao sair, causando um atraso ao sair de um jogo.',
    'gliden64_tx_save_cache_title': 'Salvar cache de textura no disco',
    'gliden64_use_native_resolution_factor_1x': '1x',
    'gliden64_use_native_resolution_factor_2x': '2x',
    'gliden64_use_native_resolution_factor_3x': '3x',
    'gliden64_use_native_resolution_factor_4x': '4x',
    'gliden64_use_native_resolution_factor_off': 'Desligado',
    'gliden64_use_native_resolution_factor_title': 'Usar fator de resolução nativa',
    'gliden64_widescreen_hack_title': 'Hack de widescreen',
    'importExportActivity_exportCheatsAndProfiles': 'Exportar Cheats e Perfis',
    'importExportActivity_exportDialogTitle': 'Exportando Dados',
    'importExportActivity_exportDumpedTextures': 'Exportar Texturas Despejadas',
    'importExportActivity_exportGameData': 'Exportar Dados de Jogo',
    'importExportActivity_importCheatsAndProfiles': 'Importar Cheats e Perfis',
    'importExportActivity_importDialogTitle': 'Importando Dados',
    'importExportActivity_importGameData': 'Importar Dados de Jogo',
    'importExportActivity_importTouchscreenGraphics': 'Importar Gráficos de Touchscreen',
    'importExportActivity_invalidCustomSkinFile': 'Arquivo de skin de gráficos de touchscreen inválido',
    'importExportActivity_invalidGameDataFolder': 'Pasta de GameData inválida, a pasta deve ser a pasta GameData exportada.',
    'importExportActivity_invalidProfilesFolder': 'Pasta de Perfis inválida, a pasta deve ser a pasta de Perfis exportada.',
    'importExportActivity_title': 'Importar/Exportar Dados',
    'inGameMenuSetting_entryBackKey': 'Quando a tecla voltar é pressionada',
    'inGameMenuSetting_entrySwipe': 'Quando o gesto de deslizar é usado',
    'inGameMenuSetting_title': 'Mostrar menu no jogo',
    'inputBackMappable_summary': 'Permitir que a tecla voltar seja mapeada para controles, isso forçará o uso do gesto de deslizar para o menu no jogo',
    'inputBackMappable_title': 'Tecla voltar mapeável',
    'inputHoldControllerMenuKey_summary': 'Segure os botões do controle por 3 segundos para que certas funções tenham efeito, como o botão de menu.',
    'inputHoldControllerMenuKey_title': 'Segurar botões do controle para funções',
    'inputMapActivity_decrementSlot': 'Decrementar slot',
    'inputMapActivity_toggle_sensor': 'Alternar sensor',
    'inputMenuMappable_summary': 'Permitir que a tecla menu seja mapeada para controles, isso forçará o uso do gesto de deslizar para o menu no jogo',
    'inputMenuMappable_title': 'Tecla menu mapeável',
    'inputShareController_entryNo': 'Não',
    'inputShareController_entryYes': 'Sim',
    'inputUseRaphnetAdapter_summary': 'Se um adaptador Raphnet for encontrado, ele será usado sobre outros controles no modo de acesso USB direto.',
    'inputUseRaphnetAdapter_title': 'Usar acesso USB direto do adaptador Raphnet',
    'iplRom64ddPath_title': 'IPL 64DD',
    'japanIplRom64ddPath_title': 'IPL 64DD (J)',
    'libraryCountryFilterAustralia_title': 'Austrália',
    'libraryCountryFilterEurope_title': 'Europa',
    'libraryCountryFilterFrance_title': 'França',
    'libraryCountryFilterGermany_title': 'Alemanha',
    'libraryCountryFilterItaly_title': 'Itália',
    'libraryCountryFilterJapan_title': 'Japão',
    'libraryCountryFilterKorea_title': 'Coreia',
    'libraryCountryFilterSpain_title': 'Espanha',
    'libraryCountryFilterUnknown_title': 'Desconhecido',
    'libraryCountryFilterUsa_title': 'EUA',
    'libraryCountryFilter_title': 'Filtro de país do jogo',
    'libraryScale_title': 'Escala da arte da capa',
    'menuItem_Clear': 'Limpar Pacotes de Textura',
    'menuItem_ClearShaderCache': 'Limpar Cache de Shader',
    'menuItem_ConfirmationClearShaderCache': 'Tem certeza de que deseja limpar o cache do shader?',
    'menuItem_Extract': 'Adicionar Pacote de Textura',
    'menuItem_Tools': 'Ferramentas',
    'menuItem_auto': 'Auto',
    'menuItem_buttonsConfiguration': 'Configuração de botões',
    'menuItem_fileLoadAutoSave': 'Carregar do salvamento automático…',
    'menuItem_pak_empty': 'Vazio',
    'menuItem_pak_mem': 'Memory Pak',
    'menuItem_pak_rumble': 'Rumble Pak',
    'menuItem_pak_transfer': 'Transfer Pak',
    'menuItem_paks_transfer': 'Transfer Paks',
    'menuItem_paks_transfer_player1_ram': 'RAM do Gameboy do Jogador 1',
    'menuItem_paks_transfer_player1_rom': 'ROM do Gameboy do Jogador 1',
    'menuItem_paks_transfer_player2_ram': 'RAM do Gameboy do Jogador 2',
    'menuItem_paks_transfer_player2_rom': 'ROM do Gameboy do Jogador 2',
    'menuItem_paks_transfer_player3_ram': 'RAM do Gameboy do Jogador 3',
    'menuItem_paks_transfer_player3_rom': 'ROM do Gameboy do Jogador 3',
    'menuItem_paks_transfer_player4_ram': 'RAM do Gameboy do Jogador 4',
    'menuItem_paks_transfer_player4_rom': 'ROM do Gameboy do Jogador 4',
    'menuItem_player_four': 'Jogador 4',
    'menuItem_player_one': 'Jogador 1',
    'menuItem_player_three': 'Jogador 3',
    'menuItem_player_two': 'Jogador 2',
    'menuItem_search': 'Procurar',
    'menuItem_selectSlot': 'Selecionar Slot',
    'menuItem_select_profiles': 'Selecionar Perfis',
    'menuItem_sensitivity_x': 'Sensibilidade do eixo X',
    'menuItem_sensitivity_y': 'Sensibilidade do eixo Y',
    'menuItem_sensorConfiguration': 'Configuração do sensor',
    'netplayPlayers_title': 'Jogadores',
    'netplayServerInfo_title': 'Informações do Servidor',
    'netplayServers_title': 'Servidores Netplay',
    'netplayWaitingOnServer_title': 'Esperando o anfitrião iniciar o jogo…',
    'netplay_advanced': 'Avançado',
    'netplay_code': 'Código',
    'netplay_codeNotFound': 'O código não foi encontrado!',
    'netplay_codeRetrieveFailure': 'Não foi possível obter o código!',
    'netplay_connect': 'Conectar',
    'netplay_enterCode': 'Inserir Código',
    'netplay_enterIp': 'Inserir IP',
    'netplay_getCode': 'Obter Código',
    'netplay_hostAddress': 'Endereço',
    'netplay_hostPort1': 'Porta 1',
    'netplay_hostPort2': 'Porta 2',
    'netplay_romMd5Mismatch': 'O jogo do servidor não corresponde!',
    'netplay_running_title': 'Netplay está rodando',
    'netplay_serverVersionMismatch': 'A versão do netplay do servidor não corresponde à do cliente!',
    'netplay_toastDesyncDetected': 'Os jogadores dessincronizaram! Saia do jogo se vir problemas.',
    'parallel_deinterlacing_entry_bob': 'Bob',
    'parallel_deinterlacing_entry_weave': 'Weave',
    'parallel_deinterlacing_title': 'Método de desentrelaçamento',
    'parallel_downscale_entry_disabled': 'Desativado',
    'parallel_downscale_entry_eight': '1/8',
    'parallel_downscale_entry_fourth': '1/4',
    'parallel_downscale_entry_half': '1/2',
    'parallel_downscale_title': 'Fator de redução, reduz a saída após VI, equivalente a SSAA',
    'parallel_native_res_text_rect_summary': 'Primitivas TEX_RECT geralmente devem ser renderizadas na resolução nativa para evitar costuras',
    'parallel_native_res_text_rect_title': 'Resolução nativa TEX_RECT',
    'parallel_native_texture_lod_summary': 'Usar o cálculo de LOD de textura nativa ao aumentar a escala, efetivamente um viés de LOD',
    'parallel_native_texture_lod_title': 'LOD de textura nativa',
    'parallel_overscan_crop_title': 'Quantidade de pixels de overscan para cortar',
    'parallel_superscaling_dithering_title': 'Superscaling de pontilhamento ao fazer upsampling',
    'parallel_superscaling_readbacks_title': 'Superscaling de readbacks ao fazer upsampling',
    'parallel_synchronous_title': 'Sincronizar RDP e CPU (lento)',
    'parallel_upscaling_entry_2x': '2x',
    'parallel_upscaling_entry_4x': '4x',
    'parallel_upscaling_entry_8x': '8x',
    'parallel_upscaling_entry_None': 'Nenhum',
    'parallel_upscaling_title': 'Upscaling',
    'parallel_vi_antialiasing_summary': 'Suaviza as bordas dos polígonos',
    'parallel_vi_antialiasing_title': 'Anti-aliasing VI',
    'parallel_vi_bilinear_scaling_title': 'Escalonamento bilinear VI',
    'parallel_vi_dedither_title': 'Dedither VI',
    'parallel_vi_divot_filter_summary': 'Limpa pixels pretos perdidos',
    'parallel_vi_divot_filter_title': 'Filtro divot VI',
    'parallel_vi_gamma_dither_title': 'Dither de gama VI',
    'pathDeletingFilesTask_title': 'Excluindo arquivos…',
    'pathHiResTexturesTask_errorMessageInvalidHTC': 'Erro: O arquivo HTC deve corresponder a este formato [GAME_HEADER]__HIRESTEXTURES.htc',
    'pathHiResTexturesTask_select_zip': 'Selecione o arquivo ZIP, 7Zip, HTS ou HTC contendo o pacote de texturas de alta resolução',
    'pathHiResTexturesTask_start_file_picker': 'Selecionar arquivo',
    'playerMap_deviceNotConnected': 'Não Conectado',
    'playerMap_useDefaultPlayerMap_summary': 'Desmarque para especificar o mapeamento de jogador personalizado para este jogo',
    'playerMap_useDefaultPlayerMap_title': 'Usar mapeamento de jogador padrão',
    'preferenceAdd_title': 'Adicionar',
    'preferenceRemove_title': 'Remover',
    'relativeAnalog_summary': 'Cada vez que o joystick analógico da tela de toque é tocado, o joystick é recentralizado',
    'relativeAnalog_title': 'Joystick de tela de toque relativo',
    'roomTcpPort_title': 'Porta TCP da Sala',
    'rsp_cxd4_hle': 'CXD4 HLE Vídeo',
    'rsp_cxd4_lle': 'CXD4 LLE Vídeo',
    'rsp_hle': 'HLE',
    'rsp_parallel': 'Parallel',
    'rsp_title': 'RSP',
    'scanRomsDialog_no_saf': 'Nenhum seletor de arquivos do sistema detectado, coloque suas ROMs na seguinte pasta: ',
    'scanRomsDialog_scanSubdirectories': 'Escanear subdiretórios',
    'scanRomsDialog_select_file': 'Selecionar Arquivo',
    'scanRomsDialog_select_folder': 'Selecionar Pasta',
    'screenAdvanced_CountPerOpDefault_summary': 'Modificar isso altera o timing do jogo, valores menores podem fazer overclock no jogo, mas podem causar instabilidade.',
    'screenAdvanced_CountPerOpDefault_title': 'Usar contagem padrão por operação',
    'screenAdvanced_CountPerOpDenDefault_summary': 'Modificar isso faz o overclock do processador R4300 por um fator de 2 cada vez que o valor é incrementado, 0 é sem overclock.',
    'screenAdvanced_CountPerOpDenDefault_title': 'Usar fator de overclock padrão',
    'screenAdvanced_CountPerOpDen_title': 'Fator de Overclock',
    'screenAdvanced_CountPerOp_title': 'Contagem por operação',
    'screenAdvanced_ForceAlignmentOfPiDma_summary': 'Necessário para alguns hacks de ROM, deixe ativado para usar o padrão do jogo.',
    'screenAdvanced_ForceAlignmentOfPiDma_title': 'Forçar Alinhamento de PI DMA',
    'screenAdvanced_IgnoreTlbExceptions_summary': 'Necessário para alguns hacks de ROM ou jogos de Zelda. Deixe desativado caso contrário.',
    'screenAdvanced_IgnoreTlbExceptions_title': 'Ignorar exceções de TLB',
    'screenAdvanced_RandomizeInterrupts_summary': 'Aleatoriza interrupções para que jogos que possuem elementos aleatórios funcionem corretamente.',
    'screenAdvanced_RandomizeInterrupts_title': 'Aleatorizar Interrupções',
    'screenAdvanced_ViRefreshRateDefault_summary': 'Modificar isso altera o timing do jogo, isso pode afetar alguns relógios internos do jogo, reiniciar o jogo é necessário para que isso tenha efeito.',
    'screenAdvanced_ViRefreshRateDefault_title': 'Usar taxa de atualização VI padrão',
    'screenAdvanced_ViRefreshRate_title': 'Taxa de atualização VI',
    'screenAdvanced_title': 'Avançado',
    'sensorConfig_activateOnStart': 'Ativar no início do jogo',
    'sensorConfig_angle': 'Ângulo de repouso (°)',
    'sensorConfig_axisCustom': 'Personalizado',
    'sensorConfig_axisDisabled': 'Desativado',
    'sensorConfig_hideJoystick': 'Ocultar quando o sensor estiver ativo',
    'sensorConfig_invertAxis': 'Inverter eixo',
    'sensorConfig_joystickXEmulation': 'Emulação do eixo X do joystick',
    'sensorConfig_joystickYEmulation': 'Emulação do eixo Y do joystick',
    'sensorConfig_sensorX': 'Usar eixo X do acelerômetro',
    'sensorConfig_sensorY': 'Usar eixo Y do acelerômetro',
    'serverTcpUdpPort_title': 'Porta UDP/TCP do Servidor',
    'shadersBlur9x9_summary': 'Efeito de desfoque, isso pode ser caro em desempenho.',
    'shadersBlur9x9_title': 'Desfoque',
    'shadersCrtGeom_summary': 'Aproxima a aparência de um CRT, isso pode ser caro em desempenho.',
    'shadersCrtGeom_title': 'CRT Geometry',
    'shadersFxaa_summary': 'Anti-aliasing aproximado rápido, impacto médio no desempenho.',
    'shadersFxaa_title': 'FXAA',
    'shadersN64Dither_summary': 'Aproximação do filtro N64 VI, impacto médio no desempenho.',
    'shadersN64Dither_title': 'N64 Dither',
    'shadersNone_summary': 'Nenhuma alteração na saída do jogo',
    'shadersNone_title': 'Nenhum',
    'shadersPass_title': 'Passagem',
    'shadersPasses_title': 'Passagens de Shader',
    'shadersScaleFx_summary': 'ScaleFX é um algoritmo de interpolação de bordas especializado em pixel art.',
    'shadersScaleFx_title': 'ScaleFX',
    'shadersScale_title': 'Fator de escala do shader',
    'shadersScanlines_summary': 'Linhas de varredura simples que têm baixo impacto no desempenho.',
    'shadersScanlines_title': 'Scanlines',
    'shadersTestPattern_summary': 'Padrão de teste para ver o efeito do shader, nenhuma saída do jogo será exibida.',
    'shadersTestPattern_title': 'Padrão de Teste',
    'startNetplay_title': 'Iniciar',
    'support64dd_summary': 'Ativa o suporte para 64DD',
    'support64dd_title': 'Suporte 64DD',
    'toast_movingSlot': 'Movendo para o slot %1$d…',
    'toast_not_done_shutting_down': 'Aguarde, salvando cache de textura',
    'toast_paused': 'Pausado…',
    'toast_running': 'Rodando…',
    'toast_shutting_down': 'Salvando cache de textura…',
    'touchscreenAutoHideEnabled_summary': 'Ocultar botões quando não usados pelo número de segundos especificado.',
    'touchscreenAutoHideEnabled_title': 'Ocultar botões quando não usados',
    'touchscreenAutoHide_title': 'Número de segundos antes de ocultar os botões da tela de toque',
    'touchscreenInvertTouchXAxis_summary': 'Inverter eixo X',
    'touchscreenInvertTouchYAxis_summary': 'Inverter eixo Y',
    'touchscreenProfileActivity_ScaleSlider': 'Escalonamento: %1$d %%',
    'touchscreenProfileActivity_menuTitle': 'Escolha uma opção',
    'touchscreenProfileDpad_title': 'Perfil de tela de toque (D-pad)',
    'touchscreenStyle_entry3DSXL': 'Estilo 3DS XL',
    'touchscreenStyle_entryBlack': 'Preto',
    'touchscreenStyle_entryColored': 'Colorido',
    'touchscreenStyle_entryFlat': 'Plano',
    'touchscreenStyle_entryGameCube': 'Estilo Gamecube',
    'touchscreenStyle_entryHiRes': 'Alta Resolução',
    'touchscreenStyle_entryJoshaGibs': 'Estilo JoshaGibs',
    'touchscreenStyle_entryNewd': 'NewD',
    'touchscreenStyle_entrySwitch': 'Estilo Switch',
    'touchscreenStyle_entryWhite': 'Branco',
    'touchscreenStyle_entryWiiU': 'Estilo WiiU',
    'useFlatGameDataPath_summary': 'Manter todos os slots salvos, capturas de tela e salvamentos no jogo na mesma pasta',
    'useFlatGameDataPath_title': 'Usar estrutura de pasta de dados de jogo plana',
    'useHighPriorityThread_summary': 'O núcleo rodará usando uma thread de alta prioridade, isso pode causar travamentos em alguns dispositivos',
    'useHighPriorityThread_title': 'Usar thread de alta prioridade',
    'useUpnpToMapPort_summary': 'Usar UPnP ou NAT/PMP para mapear portas externas automaticamente',
    'useUpnpToMapPort_title': 'Mapear portas externas automaticamente',
    'videoPlugin_entryAngrylion': 'angrylion-rdp-plus\\n<small>(renderizador de software angrylion-rdp-plus)</small>',
    'videoPlugin_entryGliden64': 'gliden64\\n<small>(GLideN64 beta)</small>',
    'videoPlugin_entryParallel': 'Parallel\\n<small>(renderizador vulkan Parallel)</small>',
    'touchscreenStyle_entryCustom': 'Personalizado'
}

# ES (Spanish)
es_translations = {
    'angrylion_busyloop_title': 'Bucle ocupado mientras se espera el trabajo',
    'angrylion_compatibility_mode_fast': 'Rápido',
    'angrylion_compatibility_mode_moderate': 'Moderado',
    'angrylion_compatibility_mode_slow': 'Lento',
    'angrylion_compatibility_mode_title': 'Modo de compatibilidad',
    'angrylion_hide_overscan_title': 'Ocultar sobreexploración',
    'angrylion_num_workers_title': 'Número de hilos de trabajo',
    'angrylion_parallel_mode_title': 'Modo multihilo',
    'angrylion_vi_integer_scaling_title': 'Escalado de enteros',
    'angrylion_vi_interpolation_entry_linear': 'Lineal',
    'angrylion_vi_interpolation_entry_nearest_neighbor': 'Vecino más cercano',
    'angrylion_vi_interpolation_title': 'Interpolación VI',
    'angrylion_vi_mode_entry_coverage': 'Cobertura',
    'angrylion_vi_mode_entry_depth': 'Profundidad',
    'angrylion_vi_mode_entry_filtered': 'Filtrado',
    'angrylion_vi_mode_entry_unfiltered': 'Sin filtrar',
    'angrylion_vi_mode_title': 'Modo VI',
    'audioSamplingType_soundtouch': 'SoundTouch',
    'audioSamplingType_trivial': 'Trivial',
    'buttonsConfig_buttonsAB': 'Botones A/B',
    'buttonsConfig_buttonsC': 'Botones C',
    'buttonsConfig_separate': 'Usar botones separados',
    'categoryAngrylion_title': 'Ajustes de Angrylion RDP Plus',
    'categoryGlide64Advanced_title': 'Ajustes avanzados de Glide64',
    'categoryParallel_title': 'Ajustes de Parallel RDP',
    'cheatEditor_add': 'Añadir truco',
    'cheatEditor_add_advanced': 'Añadir truco avanzado',
    'cheatEditor_add_cheats': 'Añadir truco',
    'cheatEditor_add_option': 'Añadir opción',
    'cheatEditor_edit1': 'Editar truco',
    'cheatEditor_edit2': 'Edición avanzada de trucos',
    'cheatEditor_hint_cheatAddress': 'Dirección',
    'cheatEditor_hint_cheatData': 'Introducir datos del truco',
    'cheatEditor_hint_cheatNotes': 'Notas del truco (opcional)',
    'cheatEditor_hint_cheatTitle': 'Título del truco',
    'cheatEditor_hint_optionData': 'Introducir datos de la opción',
    'cheatEditor_hint_value': 'Valor',
    'cheatEditor_hint_value_description': 'Descripción',
    'cheatEditor_invalid_value': 'N/D',
    'cheatEditor_remove_option': 'Eliminar opción',
    'controller_buttonSensor': 'Botón de alternar sensor',
    'disk64ddPath_title': 'Disco 64DD (ndd)',
    'displayResolution_entry1440x1080': '1440 x 1080',
    'displayResolution_entry1920x1440': '1920 x 1440',
    'displayResolution_entry2160x1620': '2160 x 1620',
    'displayResolution_entry2880x2160': '2880 x 2160',
    'displayResolution_entry3840x2880': '3840 x 2880',
    'displayResolution_entry4320x3240': '4320 x 3240',
    'displayResolution_entry5120x3840': '5120 x 3840',
    'displayResolution_entry5760x4320': '5760 x 4320',
    'glide64mk2_adjust_aspect_title': 'Ajustar aspecto de pantalla para modo panorámico',
    'glide64mk2_alt_tex_size_title': 'Método alternativo de tamaño de textura',
    'glide64mk2_aspect_force_16_9': 'Forzar 16:9',
    'glide64mk2_aspect_force_4_3': 'Forzar 4:3',
    'glide64mk2_aspect_original': 'Original',
    'glide64mk2_aspect_stretch': 'Estirar',
    'glide64mk2_aspect_title': 'Relación de aspecto',
    'glide64mk2_buff_clear_title': 'Limpiar búfer en cada fotograma',
    'glide64mk2_clip_zmax_title': 'Activar recorte de plano lejano',
    'glide64mk2_clip_zmin_title': 'Activar recorte z cercano',
    'glide64mk2_correct_viewport_title': 'Forzar viewport positivo',
    'glide64mk2_decrease_fillrect_edge_title': 'Reducir tamaño de fillrect en 1',
    'glide64mk2_detect_cpu_write_title': 'Mostrar imágenes escritas directamente por la CPU',
    'glide64mk2_disable': 'Desactivar',
    'glide64mk2_enable': 'Activar',
    'glide64mk2_fast_crc_title': 'Usar algoritmo CRC rápido',
    'glide64mk2_fb_crc_mode_disable': 'Desactivar cálculo de CRC',
    'glide64mk2_fb_crc_mode_fast': 'Cálculo de CRC rápido',
    'glide64mk2_fb_crc_mode_safe': 'Cálculo de CRC seguro',
    'glide64mk2_fb_crc_mode_title': 'Establecer modo CRC del framebuffer',
    'glide64mk2_fb_hires_title': 'Emulación de búfer de fotogramas por hardware',
    'glide64mk2_fb_read_alpha_title': 'Leer alfa del framebuffer',
    'glide64mk2_fb_read_always_title': 'Leer framebuffer en cada fotograma (puede ser lento, usar solo para efectos que lo necesiten)',
    'glide64mk2_fb_render_title': 'Activar renderizado de profundidad por software',
    'glide64mk2_fb_smart_title': 'Framebuffer inteligente',
    'glide64mk2_filtering_automatic': 'Automático',
    'glide64mk2_filtering_force_bilinear': 'Forzar bilineal',
    'glide64mk2_filtering_force_point_samples': 'Forzar muestreo por puntos',
    'glide64mk2_filtering_title': 'Modo de filtrado',
    'glide64mk2_fog_title': 'Niebla',
    'glide64mk2_force_calc_sphere_title': 'Usar solo mapeo esférico',
    'glide64mk2_force_microcheck_title': 'Comprobar microcódigo cada fotograma',
    'glide64mk2_force_quad3d_title': 'Forzar comando 0xb5 a ser quad, no línea 3D',
    'glide64mk2_game_default': 'Predeterminado del juego',
    'glide64mk2_hires_buf_clear_title': 'Limpiar búferes de fotogramas de textura auxiliares',
    'glide64mk2_ignore_aux_copy_title': 'No copiar búferes de fotogramas auxiliares',
    'glide64mk2_increase_texrect_edge_title': 'Forzar tamaño de texrect a valor entero',
    'glide64mk2_lodmode_fast': 'Rápido',
    'glide64mk2_lodmode_precise': 'Preciso',
    'glide64mk2_lodmode_title': 'Cálculo de LOD',
    'glide64mk2_n64_z_scale_title': 'Escalar valor z del vértice antes de escribir en el búfer de profundidad',
    'glide64mk2_old_style_adither_title': 'Aplicar dither alfa independientemente de alpha_dither_mode',
    'glide64mk2_optimize_texrect_title': 'Renderizado rápido de texrect con hwfbe',
    'glide64mk2_pal230_title': 'Establecer escala especial para juegos PAL',
    'glide64mk2_read_back_to_screen_mode1': 'Modo 1',
    'glide64mk2_read_back_to_screen_mode2': 'Modo 2',
    'glide64mk2_read_back_to_screen_title': 'Renderizar búfer de fotogramas de N64 como textura',
    'glide64mk2_stipple_mode_disable': 'Desactivar',
    'glide64mk2_stipple_mode_pattern': 'Patrón',
    'glide64mk2_stipple_mode_rotate': 'Rotar',
    'glide64mk2_stipple_mode_title': 'Modo de emulación de alfa punteado 3DFX',
    'glide64mk2_swapmode_conditional': 'Intercambiar búferes cuando se cumplan ciertas condiciones. Evita parpadeos',
    'glide64mk2_swapmode_mix': 'Mezcla de los dos primeros métodos',
    'glide64mk2_swapmode_title': 'Método de intercambio de búfer',
    'glide64mk2_swapmode_vi_ocurred': 'Intercambiar búferes cuando ocurra la interrupción vertical',
    'glide64mk2_texture_correction_title': 'Activar emulación de corrección de textura de perspectiva',
    'glide64mk2_use_sts1_only_title': 'Usar solo el primer SETTILESIZE',
    'glide64mk2_useless_is_useless_title': 'Manejar fb sin cambios',
    'glide64mk2_wrpAnisotropic_16x': '16x',
    'glide64mk2_wrpAnisotropic_1x': '1x',
    'glide64mk2_wrpAnisotropic_2x': '2x',
    'glide64mk2_wrpAnisotropic_4x': '4x',
    'glide64mk2_wrpAnisotropic_8x': '8x',
    'glide64mk2_wrpAnisotropic_title': 'Ajuste de filtrado anisotrópico',
    'glide64mk2_zmode_compare_less_title': 'Forzar comprobación estricta en prueba de búfer de profundidad',
    'inputMapActivity_decrementSlot': 'Ranura anterior',
    'inputMapActivity_toggle_sensor': 'Alternar sensor',
    'iplRom64ddPath_title': 'IPL 64DD',
    'japanIplRom64ddPath_title': 'IPL 64DD (J)',
    'menuItem_buttonsConfiguration': 'Configuración de botones',
    'menuItem_pak_empty': 'Vacío',
    'menuItem_pak_mem': 'Memory Pak',
    'menuItem_pak_rumble': 'Rumble Pak',
    'menuItem_pak_transfer': 'Transfer Pak',
    'menuItem_paks_transfer': 'Transfer Paks',
    'menuItem_paks_transfer_player1_ram': 'RAM de Gameboy del Jugador 1',
    'menuItem_paks_transfer_player1_rom': 'ROM de Gameboy del Jugador 1',
    'menuItem_paks_transfer_player2_ram': 'RAM de Gameboy del Jugador 2',
    'menuItem_paks_transfer_player2_rom': 'ROM de Gameboy del Jugador 2',
    'menuItem_paks_transfer_player3_ram': 'RAM de Gameboy del Jugador 3',
    'menuItem_paks_transfer_player3_rom': 'ROM de Gameboy del Jugador 3',
    'menuItem_paks_transfer_player4_ram': 'RAM de Gameboy del Jugador 4',
    'menuItem_paks_transfer_player4_rom': 'ROM de Gameboy del Jugador 4',
    'parallel_deinterlacing_entry_bob': 'Bob',
    'parallel_deinterlacing_entry_weave': 'Weave',
    'parallel_deinterlacing_title': 'Método de desentrelazado',
    'parallel_downscale_entry_disabled': 'Desactivado',
    'parallel_downscale_entry_eight': '1/8',
    'parallel_downscale_entry_fourth': '1/4',
    'parallel_downscale_entry_half': '1/2',
    'parallel_downscale_title': 'Factor de reducción, reduce la salida después de VI, equivalente a SSAA',
    'parallel_native_res_text_rect_summary': 'Las primitivas TEX_RECT generalmente deben renderizarse a resolución nativa para evitar costuras',
    'parallel_native_res_text_rect_title': 'Resolución nativa TEX_RECT',
    'parallel_native_texture_lod_summary': 'Usar el cálculo de LOD de textura nativa al escalar, efectivamente un sesgo de LOD',
    'parallel_native_texture_lod_title': 'LOD de textura nativa',
    'parallel_overscan_crop_title': 'Cantidad de píxeles de sobreexploración para recortar',
    'parallel_superscaling_dithering_title': 'Superscaling de dither al sobremuestrear',
    'parallel_superscaling_readbacks_title': 'Superscaling de lecturas al sobremuestrear',
    'parallel_synchronous_title': 'Sincronizar RDP y CPU (lento)',
    'parallel_upscaling_entry_2x': '2x',
    'parallel_upscaling_entry_4x': '4x',
    'parallel_upscaling_entry_8x': '8x',
    'parallel_upscaling_entry_None': 'Ninguno',
    'parallel_upscaling_title': 'Escalado',
    'parallel_vi_antialiasing_summary': 'Suaviza los bordes de los polígonos',
    'parallel_vi_antialiasing_title': 'Anti-aliasing VI',
    'parallel_vi_bilinear_scaling_title': 'Escalado bilineal VI',
    'parallel_vi_dedither_title': 'Dedither VI',
    'parallel_vi_divot_filter_summary': 'Limpia píxeles negros sueltos',
    'parallel_vi_divot_filter_title': 'Filtro divot VI',
    'parallel_vi_gamma_dither_title': 'Dither de gamma VI',
    'playerMap_deviceNotConnected': 'No conectado',
    'rsp_cxd4_hle': 'Vídeo CXD4 HLE',
    'rsp_cxd4_lle': 'Vídeo CXD4 LLE',
    'rsp_hle': 'HLE',
    'rsp_parallel': 'Parallel',
    'rsp_title': 'RSP',
    'toast_movingSlot': 'Moviendo a la ranura %1$d…',
    'touchscreenProfileActivity_ScaleSlider': 'Escalado: %1$d %%',
    'touchscreenProfileActivity_menuTitle': 'Elige una opción',
    'touchscreenStyle_entryCustom': 'Personalizado',
    'videoPlugin_entryAngrylion': 'angrylion-rdp-plus\\n<small>(renderizador de software angrylion-rdp-plus)</small>',
    'videoPlugin_entryGliden64': 'gliden64\\n<small>(GLideN64 beta)</small>',
    'videoPlugin_entryParallel': 'Parallel\\n<small>(renderizador vulkan Parallel)</small>'
}

pt_path = 'app/src/main/res/values-pt/strings.xml'
pt_kv = get_kv(pt_path)
write_xml(pt_path, en_kv, pt_kv, pt_translations)

pt_br_path = 'app/src/main/res/values-pt-rBR/strings.xml'
pt_br_kv = get_kv(pt_br_path)
write_xml(pt_br_path, en_kv, pt_br_kv, pt_translations)

es_path = 'app/src/main/res/values-es/strings.xml'
es_kv = get_kv(es_path)
write_xml(es_path, en_kv, es_kv, es_translations)

print('Successfully updated PT, PT-BR and ES translations.')
