
android {
    compileSdkVersion 36
    ndkVersion="26.1.10909125"

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 29
        versionCode = 338
        versionName = "3.0.338"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
